### ISSUE TITLE
purell module is no longer maintained

### ISSUE THREAD

**Issue by gkarthiks** [go-openapi/jsonreference#10]
This is a proactive issue opened to bring to the maintainers' knowledge about the maintenance status of the `purell` package.

The purell package used in the jsonreference package is not maintained anymore and looking for maintainers.

https://github.com/go-openapi/jsonreference/blob/28a8ff900147568dc266d4cd84e062750e44f161/reference.go#L117

We at https://github.com/kubernetes/kubernetes/pull/103801 project moved the logic inside our code base and removed the direct dependency. 

So we are hoping that the jsonreference will also consider in-sourcing that code logic. 

### References:

purell issue:  https://github.com/PuerkitoBio/purell/issues/33
Kubernetes Issue: https://github.com/kubernetes/kubernetes/issues/103068

**Note**: Happy to create a PR, please let me know the path forward.

**Comment by gkarthiks** [comment]
Apologies for the ping. But @casualjim @gbjk @honza @frapposelli can any one of you please provide your opinion?

**Comment by erraggy** [comment]
Judging by the purell implementation, all that's needed to be applied are:
FlagLowercaseHost
FlagLowercaseScheme
FlagRemoveDefaultPort
FlagRemoveDuplicateSlashes

Since the `url.Parse` takes care of all the others defined in `FlagsSafe`.

**Comment by erraggy** [comment]
So there's the PR to remove it. Happy to make any changes maintainers would like.
