### ISSUE TITLE
current status?

### ISSUE THREAD

**Issue by pohly** [go-openapi/jsonreference#4]
While reviewing dependencies, concerns were raised that go-openapi/jsonreference is not ready for use because it is "work in progress" and only "90% done" - the status from https://github.com/go-openapi/jsonreference/blob/36d33bfe519efae5632669801b180bf1a245da3b/README.md.

Is that still an accurate description of the current state? The comment is from Jan 2, 2015 after all...

Can you clarify this and perhaps update the status? The key question is whether it is good enough for how it is used by code generated for Kubernetes APIs (`zz_generated.openapi.go`), which pulls it in through github.com/go-openapi/spec.

**Comment by fredbi** [comment]
Yes we should update this notice and advertise that this is feature complete and stable.

This code is pretty stable and just works for what it was intended to.

I believe it more the sister repo `jsonpointer` which has a "non-implemented" json nitpick:

> The 4.Evaluation part of the previous reference, starting with 'If the currently referenced value is a JSON array, the reference token MUST contain either...' is not implemented.
